### ISSUE TITLE
Create an 8.x-dev branch

### ISSUE THREAD

**Issue by geerlingguy** [acquia/blt-project#1]
It would be nice if, for testing/dev purposes, we could create a project using the latest -dev version of BLT, e.g.:

```
composer create-project acquia/blt-project=8.x-dev test --no-interaction
```

Right now running that still gets the latest stable release (not dev).

**Comment by grasmash** [comment]
Done.

blt-project now has two branches:

* `8.x-stable` which always require a stable version of BLT and will be used to cut tags
* `8.x` (available from packagist as `8.x-dev`) which will always require `8.x-dev` of BLT. 

So, for latest stable version of BLT.

`composer create-project acquia/blt-project --no-interaction MY_PROJECT`

This will grab the latest tag of blt-project, which will be cut from 8.x-stable and will require the latest BLT stable tag.

For latest dev version:

`composer create-project acquia/blt-project:8.x-dev --no-interaction MY_PROJECT`

This will grab the HEAD of 8.x for blt-project which will require 8.x-dev of BLT.

**Comment by geerlingguy** [comment]
Perfect, thanks!
