### ISSUE TITLE
How to restrict access to install.php and update.php in production?

### ISSUE THREAD

**Issue by arunavak111** [acquia/blt-project#24]
In my website its install.php is redirecting to /core/install.php and it reveals the drupal core version with status message. How can I prevent access to install.php from public users or how to add a redirection from /install.php to <front>?

I tried using .htaccess file. But it is not working.

**Comment by ba66e77** [comment]
You'll get better results asking in the main repo for the project: https://github.com/acquia/blt/issues. This repo is functionally just an installer for BLT.
