### ISSUE TITLE
Add "https://packages.drupal.org/8" (or 7) repo to default composer.json

### ISSUE THREAD

**Issue by mikeshiyan** [acquia/blt-project#4]
Problem: This is obviously needed for every Drupal project.

Proposed solution: add Drupal repository for 8 and 7 major version to corresponding branches.

**Comment by danepowell** [comment]
@mikeshiyan I'm not sure I understand the request. You just want to be able to download packages from Drupal.org? BLT already includes this repo in its composer.json, you shouldn't need that in blt-project as well (blt-project is just a wrapper for composer create-project): https://github.com/acquia/blt/blob/35c743485336bcb9d248caacc7135e70bfcf39b6/composer.required.json#L5

**Comment by mikeshiyan-lc** [comment]
Oh, that's correct.

The absence of drupal repo in the project's main composer.json confused me and my PhpStorm (with its built-in composer manager).
